apiVersion: v1
kind: Service
metadata:
  name: vespa-configserver
spec:
  selector:
    app: vespa-configserver
  ports:
    - name: vespa-tenant-port
      protocol: TCP
      port: 19071
      targetPort: 19071
  type: NodePort
