from datetime import datetime
from typing import Any

from pydantic import BaseModel
from pydantic import root_validator

from danswer.chat.models import CitationInfo
from danswer.chat.models import QADocsResponse
from danswer.chat.models import RetrievalDocs
from danswer.configs.constants import DocumentSource
from danswer.configs.constants import MessageType
from danswer.configs.constants import SearchFeedbackType
from danswer.db.enums import ChatSessionSharedStatus
from danswer.file_store.models import FileDescriptor
from danswer.llm.override_models import LLMOverride
from danswer.llm.override_models import PromptOverride
from danswer.search.models import BaseFilters
from danswer.search.models import ChunkContext
from danswer.search.models import RetrievalDetails
from danswer.search.models import SearchDoc
from danswer.search.models import Tag
from danswer.tools.models import ToolCallFinalResult


class SourceTag(Tag):
    source: DocumentSource


class TagResponse(BaseModel):
    tags: list[SourceTag]


class SimpleQueryRequest(BaseModel):
    query: str


class UpdateChatSessionThreadRequest(BaseModel):
    # If not specified, use Danswer default persona
    chat_session_id: int
    new_alternate_model: str


class ChatSessionCreationRequest(BaseModel):
    # If not specified, use Danswer default persona
    persona_id: int = 0
    description: str | None = None


class HelperResponse(BaseModel):
    values: dict[str, str]
    details: list[str] | None = None


class CreateChatSessionID(BaseModel):
    chat_session_id: int


class ChatFeedbackRequest(BaseModel):
    chat_message_id: int
    is_positive: bool | None = None
    feedback_text: str | None = None
    predefined_feedback: str | None = None

    @root_validator
    def check_is_positive_or_feedback_text(cls: BaseModel, values: dict) -> dict:
        is_positive, feedback_text = values.get("is_positive"), values.get(
            "feedback_text"
        )

        if is_positive is None and feedback_text is None:
            raise ValueError("Empty feedback received.")

        return values


"""
Currently the different branches are generated by changing the search query

                 [Empty Root Message]  This allows the first message to be branched as well
              /           |           \
[First Message] [First Message Edit 1] [First Message Edit 2]
       |                  |
[Second Message]  [Second Message of Edit 1 Branch]
"""


class CreateChatMessageRequest(ChunkContext):
    """Before creating messages, be sure to create a chat_session and get an id"""

    chat_session_id: int
    # This is the primary-key (unique identifier) for the previous message of the tree
    parent_message_id: int | None
    # New message contents
    message: str
    # file's that we should attach to this message
    file_descriptors: list[FileDescriptor]
    # If no prompt provided, uses the largest prompt of the chat session
    # but really this should be explicitly specified, only in the simplified APIs is this inferred
    # Use prompt_id 0 to use the system default prompt which is Answer-Question
    prompt_id: int | None
    # If search_doc_ids provided, then retrieval options are unused
    search_doc_ids: list[int] | None
    retrieval_options: RetrievalDetails | None
    # allows the caller to specify the exact search query they want to use
    # will disable Query Rewording if specified
    query_override: str | None = None

    # allows the caller to override the Persona / Prompt
    llm_override: LLMOverride | None = None
    prompt_override: PromptOverride | None = None

    # allow user to specify an alternate assistnat
    alternate_assistant_id: int | None = None

    # used for seeded chats to kick off the generation of an AI answer
    use_existing_user_message: bool = False

    # Per-conversation toggles for the search-quality features, default OFF and
    # independent of the assistant's own settings (the chat page exposes these
    # so a user can opt in for just this conversation). Each still requires its
    # global master switch (RERANK_ENABLED / LLM_RELEVANCE_FILTER_ENABLED).
    use_reranking: bool = False
    use_relevance_filter: bool = False

    @root_validator
    def check_search_doc_ids_or_retrieval_options(cls: BaseModel, values: dict) -> dict:
        search_doc_ids, retrieval_options = values.get("search_doc_ids"), values.get(
            "retrieval_options"
        )

        if search_doc_ids is None and retrieval_options is None:
            raise ValueError(
                "Either search_doc_ids or retrieval_options must be provided, but not both or neither."
            )

        return values


class ChatMessageIdentifier(BaseModel):
    message_id: int


class ChatRenameRequest(BaseModel):
    chat_session_id: int
    name: str | None = None


class ChatSessionUpdateRequest(BaseModel):
    sharing_status: ChatSessionSharedStatus


class RenameChatSessionResponse(BaseModel):
    new_name: str  # This is only really useful if the name is generated


class ChatSessionDetails(BaseModel):
    id: int
    name: str
    persona_id: int
    time_created: str
    shared_status: ChatSessionSharedStatus
    folder_id: int | None
    current_alternate_model: str | None = None


class ChatSessionsResponse(BaseModel):
    sessions: list[ChatSessionDetails]
    # True when more (older) sessions exist beyond this page. Omitted/False
    # means the caller has reached the end of the history.
    has_more: bool = False


class SearchFeedbackRequest(BaseModel):
    message_id: int
    document_id: str
    document_rank: int
    click: bool
    search_feedback: SearchFeedbackType | None

    @root_validator
    def check_click_or_search_feedback(cls: BaseModel, values: dict) -> dict:
        click, feedback = values.get("click"), values.get("search_feedback")

        if click is False and feedback is None:
            raise ValueError("Empty feedback received.")

        return values


class ChatMessageDetail(BaseModel):
    message_id: int
    parent_message: int | None
    latest_child_message: int | None
    message: str
    rephrased_query: str | None
    context_docs: RetrievalDocs | None
    message_type: MessageType
    time_sent: datetime
    alternate_assistant_id: str | None
    # Dict mapping citation number to db_doc_id
    citations: dict[int, int] | None
    files: list[FileDescriptor]
    tool_calls: list[ToolCallFinalResult]

    def dict(self, *args: list, **kwargs: dict[str, Any]) -> dict[str, Any]:  # type: ignore
        initial_dict = super().dict(*args, **kwargs)  # type: ignore
        initial_dict["time_sent"] = self.time_sent.isoformat()
        return initial_dict


class ChatSessionDetailResponse(BaseModel):
    chat_session_id: int
    description: str
    persona_id: int
    persona_name: str
    messages: list[ChatMessageDetail]
    time_created: datetime
    shared_status: ChatSessionSharedStatus
    current_alternate_model: str | None


class QueryValidationResponse(BaseModel):
    reasoning: str
    answerable: bool


class AdminSearchRequest(BaseModel):
    query: str
    filters: BaseFilters


class AdminSearchResponse(BaseModel):
    documents: list[SearchDoc]


class AutoSearchRequest(BaseModel):
    """A single point-in-time question for the auto-routed Search tab."""

    message: str
    # When the user explicitly picks an assistant via "@mention", its id is sent
    # here — the router (LLM selection) step is skipped and this assistant is
    # invoked directly (still ACL-re-checked on the trusted side). None => auto-route.
    persona_id: int | None = None


class AnsweredByAssistant(BaseModel):
    persona_id: int
    name: str
    display_name: str | None
    # True if the router picked this assistant; False if it fell back to the
    # all-source default persona (low confidence / no clear match).
    routed: bool
    confidence: float


class SearchedAssistant(BaseModel):
    """A next-best assistant the router ranked below the one that answered — shown
    as 'Recommended assistants' the user can chat with next if #1 wasn't right."""

    persona_id: int
    name: str
    display_name: str | None


class AutoSearchResponse(BaseModel):
    answer: str | None = None
    citations: list[CitationInfo] | None = None
    docs: QADocsResponse | None = None
    # The persisted AI message id — used to attach 👍/👎 + text feedback via the
    # existing /chat/create-chat-message-feedback endpoint.
    chat_message_id: int | None = None
    answered_by: AnsweredByAssistant
    # Next-best assistants (router ranks 2..N) offered as a chat-further affordance
    # from the SAME router call — no extra LLM call. Empty for keyword routes and
    # explicit @mentions (nothing to recommend).
    other_recommended: list[SearchedAssistant] = []
    error_msg: str | None = None
    # --- Side-by-side compare (Settings.auto_search_compare_enabled) -----------
    # True when compare applies (LLM route + gate on): tells the UI to render the
    # tabbed layout and lazy-fetch the union answer via /query/auto-search/union.
    # False => single-answer layout (keyword/@mention routes, or gate off).
    compare_enabled: bool = False
    # The assistants whose document sets the union answer should span (the router's
    # top-N picks). The UI passes these ids to the union endpoint — no re-routing,
    # so the union scope is guaranteed consistent with this response. Computing this
    # is cheap (no second answer generation), so the top-1 answer isn't held up.
    union_assistants: list[SearchedAssistant] = []


class AutoSearchUnionRequest(BaseModel):
    """Lazy second-answer request for the Search tab's compare view: answer over the
    UNION of the given assistants' document sets. Fired by the UI after the primary
    answer arrives, so the two answers never block each other."""

    message: str
    # The assistants to union — the union_assistants ids from AutoSearchResponse.
    persona_ids: list[int]


class AutoSearchUnionResponse(BaseModel):
    answer: str | None = None
    citations: list[CitationInfo] | None = None
    docs: QADocsResponse | None = None
    error_msg: str | None = None


class DanswerAnswer(BaseModel):
    answer: str | None
