apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler-service
spec:
  selector:
    app: dask-scheduler
  ports:
  - name: rpc
    protocol: TCP
    port: 8786
    targetPort: 8786
  - name: dashboard
    protocol: TCP
    port: 8787
    targetPort: 8787
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dask-scheduler-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dask-scheduler
  template:
    metadata:
      labels:
        app: dask-scheduler
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - indexcpu
      containers:
      - name: scheduler
        image: sfbrdevhelmweacr.azurecr.io/danswer/danswer-backend:vha-138
        imagePullPolicy: IfNotPresent
        command:
        - dask
        - scheduler
        - --host=0.0.0.0
        - --port=8786
        - --dashboard-address=:8787
        ports:
        - name: rpc
          containerPort: 8786
        - name: dashboard
          containerPort: 8787
        envFrom:
        - configMapRef:
            name: env-configmap
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          tcpSocket:
            port: 8786
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8786
          initialDelaySeconds: 15
          periodSeconds: 20
      tolerations:
      - effect: NoSchedule
        key: darwin
        operator: Equal
        value: indexing
