apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  selector:
    app: web-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workloadType
                operator: In
                values:
                - latest
      containers:
      - name: web-server
        image: sfbrdevhelmweacr.azurecr.io/danswer/danswer-web-server:0528-1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        # There are some extra values since this is shared between services
        # There are no conflicts though, extra env variables are simply ignored
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: danswer-secrets
              key: postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: danswer-secrets
              key: postgres_password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: danswer-secrets
              key: redis_password
        envFrom:
        - configMapRef:
            name: env-configmap
