apiVersion: apps/v1
kind: Deployment
metadata:
  name: background-beat-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: background-beat
  template:
    metadata:
      labels:
        app: background-beat
    spec:
      containers:
      - name: beat
        image: danswer-backend
        imagePullPolicy: IfNotPresent
        command:
        - celery
        - -A
        - danswer.background.celery.celery_run:celery_app
        - beat
        - --loglevel=INFO
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: postgres_user
              name: danswer-secrets
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres_password
              name: danswer-secrets
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis_password
              name: danswer-secrets
              optional: true
        envFrom:
        - configMapRef:
            name: env-configmap
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
