apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vespa-admin
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: vespa-admin
      name: vespa-internal
  serviceName: vespa-internal
  template:
    metadata:
      labels:
        app: vespa-admin
        name: vespa-internal
    spec:
      containers:
      - args:
        - services
        envFrom:
        - configMapRef:
            name: vespa-config
        image: vespa
        imagePullPolicy: Always
        name: vespa-admin
        resources:
          limits:
            memory: 2G
          requests:
            memory: 1G
        securityContext:
          runAsUser: 1000
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
