name: Tag Latest Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version (ie v0.0.1) to tag as latest'
        required: true

jobs:
  tag:
    runs-on: uipath-ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9  # v1.7.0

    - name: Login to Docker Hub
      uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7  # v1.14.1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Enable Docker CLI experimental features
      run: echo "DOCKER_CLI_EXPERIMENTAL=enabled" >> $GITHUB_ENV

    - name: Pull, Tag and Push Web Server Image
      run: |
        docker buildx imagetools create -t danswer/danswer-web-server:latest danswer/danswer-web-server:${{ github.event.inputs.version }}

    - name: Pull, Tag and Push API Server Image
      run: |
        docker buildx imagetools create -t danswer/danswer-backend:latest danswer/danswer-backend:${{ github.event.inputs.version }}
