name: Build Backend Image on Merge Group

on:
  pull_request:
    branches: [ "main" ]
  merge_group:
    types: [checks_requested]

env:
  REGISTRY_IMAGE: danswer/danswer-backend

jobs:
  build:
    # TODO: make this a matrix build like the web containers
    runs-on: 
      group: amd64-image-builders
      
    steps:
    - name: Checkout code
      uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e  # v2.8.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f  # v3.12.0

    - name: Backend Image Docker Build
      uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25  # v5.4.0
      with:
        context: ./backend
        file: ./backend/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        tags: |
          ${{ env.REGISTRY_IMAGE }}:latest
        build-args: |
          DANSWER_VERSION=v0.0.1
